### ISSUE TITLE
About "Public Domain"

### ISSUE THREAD

**Issue by donsciarra** [douglascrockford/JSON-js#101]
The term "Public Domain" is not defined in the European jurisdiction. This makes the package practically not usable in Europe and in other jurisdictions missing such definition.

Does your definition of "Public Domain" match and is in agreement with the following definition from http://unlicense.org ?

> This is free and unencumbered software released into the public domain.
> 
> Anyone is free to copy, modify, publish, use, compile, sell, or
> distribute this software, either in source code form or as a compiled
> binary, for any purpose, commercial or non-commercial, and by any
> means.
> 
> In jurisdictions that recognize copyright laws, the author or authors
> of this software dedicate any and all copyright interest in the
> software to the public domain. We make this dedication for the benefit
> of the public at large and to the detriment of our heirs and
> successors. We intend this dedication to be an overt act of
> relinquishment in perpetuity of all present and future rights to this
> software under copyright law.
> 
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
> EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
> MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
> IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
> OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
> ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
> OTHER DEALINGS IN THE SOFTWARE.
> 
> For more information, please refer to <http://unlicense.org/>

Source: http://unlicense.org/

**Comment by douglascrockford** [comment]
Public Domain is less restrictive than that.

**Comment by donsciarra** [comment]
OK, fine. What you mean then by "Public Domain"? Do you have a reference definition?

**Comment by douglascrockford** [comment]
It means that it belongs to the Public.

**Comment by donsciarra** [comment]
As in "Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means."

**Comment by AlexanderRossDe** [comment]
Hi Douglas,
do you allow your package to be used, modified and distributed in any form for both commercial and non-commercial purposes?

Just to avoid misunderstandings whether the "Public" also includes commercial use.

Thank you very much for your time!

**Comment by douglascrockford** [comment]
See https://en.wikipedia.org/wiki/Public_domain

**Comment by matjon** [comment]
Unfortunately, in Poland, by default copyright licenses expire after 5 years (article 66, paragraph 1 of Polish copyright code).

I am no one to command You around, but I would like to say that it would be really better if You specified CC0 as Your license. This would avoid any such misunderstandings.

Thank You very much for developing JSON.js.

**Comment by douglascrockford** [comment]
You are free to copy, modify, or
redistribute.
