### ISSUE TITLE
Error 60, Line 643

### ISSUE THREAD

**Issue by tpalmer0127** [douglascrockford/JSON-js#102]
I'm trying to use json2.js in a Photoshop script.  In the simplest form of the script, I only have the include
#include json2.js
When I run the script from Photoshop, I get 
Error 60; Not well-formed (invalid token).
Line 643  ->     <td id-"LC39"    etc.
I would appreciate your assistance.

**Comment by douglascrockford** [comment]
<td id-"LC39" etc. is HTML. Replace the '-' with '='.
