### ISSUE TITLE
Why can "[2.]" be parsed successfully in  json_parse.js?

### ISSUE THREAD

**Issue by linweinb** [douglascrockford/JSON-js#104]
Hi! Douglas! 
There is a problem in json_parse.js.
For example:
`json_parse("[2.]"); 
// => [2]
`
It is parsed successfully and does not throw error.
But, in the syntax of JSON, it must be at least one number after the decimal point. 
I think it must throw error.

**Comment by douglascrockford** [comment]
JSON parsers are allowed to be lenient. Can you identify an attack that this allows?
