### ISSUE TITLE
Request for an explicit license for the package

### ISSUE THREAD

**Issue by RobertPepkaSEL** [douglascrockford/JSON-js#106]
I noticed that JSON-js is dedicated to the public domain in json2.js and several other files, but doesn't have a LICENSE file or package.json file stating that it applies to the entire package. Some files don't contain this statement, such as the test.html file. Is it intended to have this entire package dedicated to the public domain?

If so, it would be helpful to have a LICENSE file for the package stating so. Additionally, you may want to consider using a specific license, such as the "CC0" - the Creative Commons "No rights reserved" license, that allows for public domain-like licensing even in places that don't have the concept of public domain code. Alternatively, an MIT style license is nearly the same, but you retain copyright.

If you're interested, I'd also be willing to put together a pull request to add a LICENSE file and/or a package.json file.

**Comment by douglascrockford** [comment]
Are you asking for permission to distribute test.html?

**Comment by akuckartz** [comment]
jsonzip.js does not contain any license or rights statement.

**Comment by RobertPepkaSEL** [comment]
Thanks for your response! :) 

I'm not particularly interested in distributing test.html. Rather, I meant that this package (the entire repo) is pulled down when NPM clones it. That means README, test.html, and jsonzip.js are being distributed (via git clone/pull) without an explicit license. I didn't think that was intentional. The idea of adding a LICENSE file to the package would help cover any other future files automatically and incidently make it easier for tools like NPM to check/display licensing.

**Comment by RobertPepkaSEL** [comment]
Sorry about that, you're absolutely right. I misread what my tool was telling me; I should be looking at https://github.com/dscape/cycle instead (it contains a fork of cycle.js, but the readme pointed me at this repo.)
