### ISSUE TITLE
BUG: loss of fidelity for larger number inputs

### ISSUE THREAD

**Issue by fulldecent** [douglascrockford/JSON-js#107]
This program fails with the following input:

# Test case

Use the following input.

```
9999999999999999999999999
```

HTML example:

```html
<html><body><script src="cycle.js"></script>
<pre><p id=output></p>
<script>
function out(s) {
    document.getElementById('output').innerHTML += s + '<br>';
}

function doTest() {
    var i, o, s, jsonObj;
    try {
        o = 9999999999999999999999999;
        out(JSON.stringify(o));

    } catch (e) {
        debugger;
        out("    name: " + e.name);
        out(" message: " + e.message);
    }
}

doTest();
</script></pre></body></html>
```

# Expected outcome

Program throws

# Actual outcome

```
1e+25
```

# Discussion

`1e+25` is not equal to `9999999999999999999999999`.

**Comment by douglascrockford** [comment]
No it is not. That is a feature of IEEE 754. Please see Chapter 2: "How Numbers Work" in _How JavaScript Works_.

**Comment by fulldecent** [comment]
Could you please clarify what is "no it is not"? Are you agreeing with the statement that "`1e+25` is not equal to `9999999999999999999999999`"?

I understand how numbers work in JavaScript. I also understand how numbers work in JSON. Numbers in JSON work like this:

![number](https://user-images.githubusercontent.com/382183/54285123-b9ac1c80-4577-11e9-8b06-26ad1ada9cfb.gif)

This library advertises in README.md:

> The files in this collection implement JSON encoders/decoders in JavaScript.

And this is incorrect because 9999999999999999999999999 is not properly decoded.

A more correct statement might be:

> The files in this collection implement JSON encoders/decoders in JavaScript, which work properly for a limited subset of JSON inputs.

**Comment by tehpsalmist** [comment]
@fulldecent if it's helpful, your very long number literal does not represent the fidelity you think it represents.

![bignumberencoding](https://user-images.githubusercontent.com/26337310/54295930-57a8e280-458a-11e9-9db4-21e7897fa878.gif)

Even more insightful, and relevant to your point, is this statement:

<img width="403" alt="Screen Shot 2019-03-13 at 12 18 54" src="https://user-images.githubusercontent.com/26337310/54296033-87f08100-458a-11e9-9014-d4cdf2b59edd.png">

The [relevant line(s)](https://github.com/douglascrockford/JSON-js/blob/03157639c7a7cddd2e9f032537f346f1a87c0f6d/json2.js#L274) in the library where the numbers are being encoded.

The issue you are identifying is not specific to this library, but a feature of the language in which this library is written, as @douglascrockford pointed out in his response.

To clarify my intentions, I personally found this question interesting and therefore thought I would share what I found on my own. I won't be following up with any other discussion here.

**Comment by fulldecent** [comment]
Thank you for sharing. That is a good illustration. Yes, this is a limitation of JavaScript.

This library claims to be able to decode JSON files. If a JSON file not decoded properly then I believe such a bug should be fixed or acknowledged and documented as a shortcoming.

At present, the file is decoded without full fidelity (i.e. it is decoded incorrectly) and without emitting an error. In other words, this library is unsafe.

**Comment by douglascrockford** [comment]
You will understand better if you read the book I referred you to.

The issue is that JavaScript itself is unable to correctly represent the value, as tehpsalmist helpfully tried to demonstrate to you. By your reasoning, it is JavaScript itself that is unsafe.

**Comment by fulldecent** [comment]
Sorry about the example. The test case is still correct. But previously I had pasted an incorrect example code, which as you have both pointed out, relied on a JavaScript integer literal which truncated the value before this library had a chance to use it.

I have now updated the example code at top to properly demonstrate the problem, where a full, valid input is given to the library.

**Comment by douglascrockford** [comment]
First do the required reading.

**Comment by fulldecent** [comment]
Will you mail me a free copy of the book. Or is this a money grab?

**Comment by fulldecent** [comment]
In JavaScript, the authoritative specification is ECMAScript 2015 explaining exactly how a string is translated to a number. This applies to the `Number()` conversion.

> Once the exact [Mathematical Value] for a String numeric literal has been determined, it is then rounded to a value of the Number type. 
> ...
> ... the Number value may be either the Number value for the MV of a literal produced by replacing each significant digit after the 20th with a 0 digit or the Number value for the MV of a literal produced by replacing each significant digit after the 20th with a 0 digit and then incrementing the literal at the 20th digit position

So in JavaScript, that is:

```js
> Number('9999999999999999999999999')
< 1e+25
```

This works as advertised.

* Reference: ECMAScript 2015 (6th Edition, ECMA-262) 7.1.3.1.1 https://www.ecma-international.org/ecma-262/6.0/#sec-runtime-semantics-mv-s

---

JSON-js is "a reference implementation" for JSON parsing in JavaScript. And the authoritative documentation is in json_parse.js at the top of the file. This states:

> This method parses a JSON text to produce an object or array. It can throw a SyntaxError exception.

The specification does not actually say *which* object or array will be returned. (Furthermore, the specification is wrong because it may also return a number or bool or null -- filed separate issue #108.) But the implicit assumption is that this will return the *correct* object or array.

The naive interpretation is that the correct data will be returned. But instead, the behavior is the same as the String to Number conversion above.

```js
<html><body><script src="json_parse.js"></script>
<pre><p id=output></p>
<script>
function out(s) {
    document.getElementById('output').innerHTML += s + '<br>';
}

try {
    out(json_parse('9999999999999999999999999'));
} catch (e) {
    debugger;
    out("    name: " + e.name);
    out(" message: " + e.message);
}
</script></pre></body></html>
```

Which outputs 

```
1e+25
```

* Reference: JSON-js reference implementation. json_parse.js. https://github.com/douglascrockford/JSON-js/blob/master/json_parse.js

---

It should not be necessary to guess that JSON-js is implemented using `Number(i)` because that is an implementation detail. (And other, safer, implementations are possible.) Instead the function should work as documented.
