### ISSUE TITLE
Unspecified behavior for large number inputs

### ISSUE THREAD

**Issue by fulldecent** [douglascrockford/JSON-js#111]
- :white_check_mark: I have purchased and read <i>How JavaScript Works</i> as required before posting this issue.
  - Proof: the first word in-text on page 8.5 is "wun".

# Documentation

The entirety of documentation for the `json_parse` function is:

> This method parses a JSON text to produce an object or array. It can throw a SyntaxError exception. 
>
> The optional reviver parameter is a function that can filter and transform the results. It receives each of the keys and values, and its return value is used instead of the original value. If it returns what it received, then the structure is not modified. If it returns undefined then the member is deleted.

> This is a function that can parse a JSON text, producing a JavaScript data structure. It is a simple, recursive descent parser. It does not use eval or regular expressions, so it can be used as a model for implementing a JSON parser in other languages.

And the entirety of in-code comments (which, IMVHO, should not be necessary as reference when calling a function) related to parsing numbers is:

> // Parse a number value. 

This issue is concerned with an ambiguity of function documentation, which is illustrated below. Several solutions are possible. 

# Test case

```javascript
<html><body>
<pre id=output></pre>
<script src="https://cdn.jsdelivr.net/gh/douglascrockford/JSON-js@master/json_parse.js" integrity="sha384-eMb7JY0D/2s6H9RrMtWRdX/5QYFyPYp7f+5Tu2k6RKq+9JoONLwrJxyJBB26lubK" crossorigin="anonymous"></script>
<script>
const pre = document.getElementById('output');
const jsonInput = '9999999999999999999999999';

try {
  const result = json_parse(jsonInput);
  pre.innerHTML += result + '<br>';
} catch (e) {
  debugger;
  pre.innerHTML += "error" + e.name + '<br>';
  pre.innerHTML += "error" + e.message + '<br>';
}
</script>
</body></html>
```

See also: [JS Bin link](https://jsbin.com/nahugukozu/edit?html,output)

# Expected outcome

None.

It is not specified in which way the input `'9999999999999999999999999'` will be "parsed".

# Actual outcome

The page outputs:

```
1e+25
```

# Notes

1. The code `let parsed = Number("9999999999999999999999999")` also produces the same output `1e+25`. The parsing behavior for the `Number()` function is specified in the ECMAScript® 2018 Language Specification, [section 7.1.3](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-tonumber-applied-to-the-string-type).

1. The way which this library handles an input of `"25"` is very reasonable and immediately obvious. In contrast, the way which this library handles an input of `"9999999999999999999999999"` is also very reasonable -- but other very reasonable implementations are possible and therefore the chosen implementation is not immediately obvious.

1. The above referenced book provides two choice quotations which motivate creating this issue:

   1. > True mastery is shown by writing good programs that are readable, maintainable, and free of error.
      >
      > *Page 0.1*

   2. > If a feature is sometimes useful and sometimes dangerous and if there is a better option then always use the better option.
      >
      > *Page 0.1*

   My application of these quotes to the instant issue requires the understing that "free of error" relates to comparing a program with its behavior as specified in documentation, and that programs which exhibit unspecified behaviors are "dangerous". Especially so for programs which assert that they are a "reference implementation".

1. I am not afraid of hard work and am happy to submit a correction, also released in public domain, if invited to do so.

**Comment by douglascrockford** [comment]
json2.js implements methods that are specified in The ECMAScript Standard, Fifth Edition. One of the fatal flaws in that standard is that it requires use of IEEE754, the source of your complaints.

This package will not change. But you are free to write a better one. For example, you can cobble the parser from JavaScript: The Good Parts with the Big Float package from How JavaScript Works to make a JSON package that handles numbers correctly.

**Comment by fulldecent** [comment]
ECMAScript Standard, Fifth Edition reliance on IEEE754 is not the source of this issue. This issue is concerned with the documentation in the function. The way I would resolve this issue is to add a sentence to the documentation.

If you are saying zero changes whatsoever will be considered here, including any documentation changes then there's not much to discuss. If that is the case, please consider to disable the issues feature on this repository or mark it as archived.
