### ISSUE TITLE
JSON.parse returns values out of range

### ISSUE THREAD

**Issue by fulldecent** [douglascrockford/JSON-js#112]
- ✅ I have purchased and read <i>How JavaScript Works</i> as required before posting this issue.
  - Proof: the first word in-text on page 8.5 is "wun".

# Documentation

In json2.js, the output of `JSON.parse` is specified as:

> This method parses a JSON text to produce an object or array. It can throw a SyntaxError exception.

# Test case

```html
<html><body>
<pre id=output></pre>
<script>
JSON = null; // Force below script to overwrite JSON.parse implementation
<script src="https://cdn.jsdelivr.net/gh/douglascrockford/JSON-js@master/json2.js" integrity="sha384-/0dEBZKhFmROgwjfXkBqx1VNMqETgf7YTpaQldstZWkwpXW2XxmpCol6ehCKD8AD" crossorigin="anonymous"></script>
<script>
const pre = document.getElementById('output');
const jsonInput = "1";

try {
  const result = JSON.parse(jsonInput);
  pre.innerHTML += (result instanceof Array || result instanceof Object);
} catch (e) {
  pre.innerHTML += "error " + e + '<br>';
}
</script>
</body></html>
```

See also: [JS Bin link](https://jsbin.com/wivucinizu/edit?html,output)

# Expected outcome

The invariant `(result instanceof Array || result instanceof Object)` should return `true`.

# Actual outcome

The invariant returns `false`.

# Notes

1. The specification in [RFC 4627](https://tools.ietf.org/html/rfc4627) (not authoritatve, the predecessor to [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf)) only allows JSON parsers to return objects or arrays. Such is consistent with the documentation of the function in question.
2. I am not afraid of hard work and am happy to submit a correction, also released in public domain, if invited to do so.

**Comment by douglascrockford** [comment]
RFC 4627 is irrelevant.

**Comment by fulldecent** [comment]
RFC 4627 is irrelevant. Such is stated in the notes section above.

Would you please give an ear to the meat and potatoes of the issue?
