### ISSUE TITLE
Include the reference to NPM package in Readme

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [douglascrockford/JSON-js#118]
Please include the reference to NPM package https://www.npmjs.com/package/json-js  in Readme.
Also can you please publish the latest version to NPM repository (last publish
4 years ago)?

**Comment by douglascrockford** [comment]
json2.js is one bitty file that won't change. NPM has profound, unsolvable secure problems. I do not recommend that anyone use it.

**Comment by MNF** [comment]
Should you remove NPM package https://www.npmjs.com/package/json-js? Or at least add to description, that you do not recommend to use the package and suggest to use the file directly?

**Comment by douglascrockford** [comment]
I have never posted anything to NPM.
