### ISSUE TITLE
Cannot parse data, error: TypeError: 

### ISSUE THREAD

**Issue by impactcolor** [douglascrockford/JSON-js#122]
Thanks for putting this together.
I'm attempting to run it in Adobe CEP.
I load it like so:
`  const json2File = `${root}/js/json2.js`;
  csiRun.evalScript(`$.evalFile('${json2File}')`);
`

I then eval a script which as been loaded like so:
`
  // execute create to html
    $('#create-html').click(function() {

      csiRun.evalScript(`setupArtTemplate()`, jsxResult => {
        csiRun.evalScript(`main('${jsxResult}')`);
      });
    })
`

This loads my script and when I run 
`  try {
    const json = '{"result":true, "count":42}';
  const obj = JSON.parse(json);
  alert(obj);
} catch (error) {
  alert(layoutDetails);
  alert('Cannot parse data, error: ' + error)
}`
I get the error:
`Cannot parse data, error: TypeError: undefined is not an object`

It appears the global JSON object isn't being created.
I've also tried including it as:
`#include "./json2.js"`
I can confirm the file does load because I put an alert in there but it does not load the JSON object to do parse or stringify.  Any idea what I'm doing wrong?

**Comment by douglascrockford** [comment]
Ask Adobe.
