### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by vigyanhoon** [douglascrockford/JSON-js#123]
Hi, Can you please add license to this repo. I can't pull some other repo due to this being a dependency.

**Comment by douglascrockford** [comment]
It is Public Domain.

**Comment by vigyanhoon** [comment]
I understand but we at our firm have automated tools for procuring the repo, once it doesn't find the license file, it rejects the procurement. Due to this I am not able to procure ember-cli-windows which somehow depends on this repo.

**Comment by douglascrockford** [comment]
You can do whatever you want with it for free. An unnecessary license will cost you $100,000. I accept PayPal.

**Comment by akuckartz** [comment]
@vigyanhoon These "automated tools" should be able to look into the source code files.
