### ISSUE TITLE
Use of falsiness

### ISSUE THREAD

**Issue by 89z** [douglascrockford/JSON-js#125]
Someone noted [1] that this code has a coercion:

https://github.com/douglascrockford/JSON-js/blob/8e8b0407e475e35942f7e9461dab81929fcc7321/json2.js#L311-L313

This seems to run against your comment of "I have stopped using falsiness" [2]. Looks like a workaround could be:

~~~js
const elem = str(i, value);
partial[i] = elem !== '' ? elem : 'null';
~~~

1. https://davidwalsh.name/fixing-coercion
2. https://youtu.be/PSGEjv3Tqo0?t=10m10s

**Comment by douglascrockford** [comment]
This code went into END OF LIFE with ES6.

**Comment by 89z** [comment]
so archive the repo?

**Comment by douglascrockford** [comment]
What do you really want?

**Comment by 89z** [comment]
With all due respect (I like your work such as `cycle.js`), I expected some snarky short remark and a quick close of the issue without discussion, and I wasnt disappointed.

You made that talk in 2014 [1], but the code in question was last touched in 2018. So you couldve removed any coercions during that 4 year period but didnt. If you dont want to touch the code, thats your business. But if youre intent that you no longer going to mess with this repo, then it makes sense to archive it. Then you dont get people like me posting dumb issues (you can post issues on archived repos).

But thats not the truth of the matter, is it? You do want to keep changing to code, as was shown 7 days ago [3]. So which is it?

1. https://youtu.be/PSGEjv3Tqo0?t=10m10s
2. https://github.com/douglascrockford/JSON-js/commit/2a76286e00cdc1e98fbc9e9ec6589563a3a4c3bb
3. https://github.com/douglascrockford/JSON-js/commit/8e8b0407e475e35942f7e9461dab81929fcc7321

**Comment by douglascrockford** [comment]
You seem really passionate about this. I will accept your change if you contribute $10,000 to Girls Who Code.

**Comment by 89z** [comment]
Hm, looks like youre still doing it

https://github.com/douglascrockford/JSCheck/blob/2a1cc723/jscheck.js#L368

**Comment by fulldecent** [comment]
@89z It's a trap. He made me buy his book to look at an issue I made. I did, with proof. Even then he didn't look at it and he just deleted my comment.

So my experience is that he is not trustworthy or following established courtesies on GitHub.
