### ISSUE TITLE
Recursive str crash

### ISSUE THREAD

**Issue by Dariusz1989** [douglascrockford/JSON-js#129]
Hey

Running this in photoshop...
```
data = {}
data["la"] = 1
data["le"] = "2"
data["lo"] = false
data["lala"] = []
var lah = []
lah.push(data)
lah.push(data)
lah.push(data)
data["lala"] = lah

ba = data
var da = []
da.push(data)
da.push(data)
ba["lala"] = da
var s = JSON.stringify(ba)
```

WIll cause stack overrun/crash. 
I take the nested arrays/dicts dont want to properly... build?

**Comment by douglascrockford** [comment]
JSON can not serialize cyclic structures.

However, https://github.com/douglascrockford/JSON-js/blob/master/cycle.js can.
