### ISSUE TITLE
False positives when detecting cyclic stucture

### ISSUE THREAD

**Issue by vsigler** [douglascrockford/JSON-js#135]
Not sure if it is not intentional, but the cyclic structure detection seems to be too simplified. Instead of checking only within the same stack, it throws an error even when there is the same object used anywhere within the object structure. See the following example:

```javascript
var aa = { "test": "tst" };
var bb = { "one" : aa, "two": aa};
JSON.stringify(bb)
```
Produces:
```
Json.ts:328 Uncaught TypeError: Converting circular structure to JSON
    at str (Json.ts:329:25)
    at str (Json.ts:375:29)
    at __webpack_modules__.7658.JSON.stringify (Json.ts:459:17)
    at <anonymous>:1:6
```

The object is prefectly fine to be serialized into json and has no cyclic structures. I would say the detection should only consider actual stack as it is traversing the serialized object.

**Comment by douglascrockford** [comment]
What is Json.ts?

**Comment by vsigler** [comment]
Ah sorry, my bad, it is `json2.js`, just a colleague changed the suffix to `ts` as the rest of our framework is in TypeScript. Just a cosmetic thing.

**Comment by douglascrockford** [comment]
File a bug report with a colleague.

**Comment by vsigler** [comment]
Ummm, should I re-raise with a better stacktrace?

Sorry, I do not follow. How is it relevant whether we use the same file naming to the actual problem of possibly incorrect cyclic structure detection?

**Comment by vsigler** [comment]
Happy now? https://github.com/douglascrockford/JSON-js/issues/136
