### ISSUE TITLE
what are the meanings of  cx and escapable?

### ISSUE THREAD

**Issue by wangyu0248** [douglascrockford/JSON-js#36]
var cx = /[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,

 escapable = /[\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,

I have looked for a while, but can't figure out the ascii means of these two RegExp, can any one tell me where i can find some usefull informations?

**Comment by felquis** [comment]
> I mean how these RegExp come from? is there any article that i can refer to ?
