### ISSUE TITLE
Avoid using eval

### ISSUE THREAD

**Issue by AndyOGo** [douglascrockford/JSON-js#75]
I quickly went through your json2 code and spot an ugly eval there.
[https://github.com/douglascrockford/JSON-js/blob/master/json2.js#L504](url)

Replace it with a function constructor and it will run faster;)

Something like this should do the trick:
`(new Function('return (' + text +');'))();`

**Comment by douglascrockford** [comment]
Where is the data?

**Comment by AndyOGo** [comment]
Data should be there, see this example:

`var func = new Function('return ({"foo": "bar"});');
var data = func();
// => Object {foo: "bar"}
`
Check out this fiddle [https://jsfiddle.net/s7420atn/](url)

**Comment by douglascrockford** [comment]
Is this a significant improvement? Is the improvement observable? What are the numbers?

**Comment by AndyOGo** [comment]
Sorry I have to admit that I'm wrong, at least concerning modern browsers. Though your fallback should only be needed in older versions who don't support it: [http://caniuse.com/#feat=json](url)
Can't provide actuall numbers for them quickly, however I was pretty sure I have tested this years ago...

[http://jsperf.com/json-eval-vs-function-constructor](url)

**Comment by douglascrockford** [comment]
Any change for the purpose of improving performance must come with data showing that performance needed to be improved, and that the change significantly improves. Any performance enhancing change that doesn't significantly improve performance is a defect that should be removed.

**Comment by brettz9** [comment]
Might this issue be reopened (and also for `cycle.js`) for the sake of allowing compatibility with pages running with strict CSP settings?

**Comment by mreinstein** [comment]
It's impossible to bundle this module via esbuild as direct eval is explicitly forbidden:  https://esbuild.github.io/content-types/#direct-eval

**Comment by douglascrockford** [comment]
JSON has been built into JavaScript since 2009. Why are you still using this?

**Comment by mreinstein** [comment]
> JSON has been built into JavaScript since 2009. Why are you still using this?

Given that text on the internet lacks tone, I'll assume you're being direct/terse rather than hostile. 

I want to serialize an in-memory object containing cyclic references, and the native JSON facilities in browsers don't handle this. `cycle.js` does. An example:

```javascript
const a = { children: [] }
a.children.push(a)
JSON.stringify(a)
```

<img width="460" alt="Screenshot 2023-11-21 at 3 58 39 PM" src="https://github.com/douglascrockford/JSON-js/assets/718067/5ad7acf4-f012-4c64-9e7b-be60d1b91451">

**Comment by mreinstein** [comment]
`cycle.js` is recommended in MDN's docs for `JSON.stringify` :

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#issue_with_serializing_circular_references

**Comment by douglascrockford** [comment]
You might not be aware of this, but I led the revolt against eval. There are very few cases where its use it indicated, such as this one, where the call to eval is conditioned on a regular expression that assures that nothing out of the way will occur.

I looked at your link, and it did not say "forbidden". It said "not recommended", which I agree with.

**Comment by mreinstein** [comment]
> You might not be aware of this, but I led the revolt against eval

I wasn't aware of that, but based on what I remember from "Javascript: The Good Parts" it's not hard to imagine you would be against eval. :)

Do you think the IETF draft or another effort might ever yield builtin support for object references?
