### ISSUE TITLE
None of the three implementations support duplicate keys

### ISSUE THREAD

**Issue by AbsolutelyFreeWeb** [douglascrockford/JSON-js#80]
I believe duplicate keys are valid json, but with an array implementation it is not supported.

Here is a valid json that throws an error:

{
	"favorite": {
		"name": "Test Page",
		"url": "www.test.com"
	},
	"folder": {
		"name": "A Category",
		"subfavorite": [{
			"name": "Another Page",
			"url": "www.test.com"
		}, {
			"name": "3rd Page",
			"url": "www.test.com"
		}]
	},
	"favorite": {
		"name": "4th Page",
		"url": "www.tomorrow.com"
	}
}

This is not supported in current JSON either (at least chrome's implementation), even worse it silently omits the duplicate key.

**Comment by douglascrockford** [comment]
Keys should not be duplicated.
