### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by mdvanes** [douglascrockford/JSON-js#85]
This might be intentional, but this package has no license file, which makes it copyrighted by default. This makes it impossible for me to use it in my project through NPM (by way of https://github.com/dscape/cycle). I, and many with me I assume, would appreciate it if a license file could be chosen, even if this makes it explicitly copyrighted, because in this case I know what steps to undertake.

Thank you in advance for your response.

**Comment by douglascrockford** [comment]
Read the source.
