### ISSUE TITLE
Question: why not expose the JSON validation as public method.

### ISSUE THREAD

**Issue by ayesham** [douglascrockford/JSON-js#95]
Curious to know why the validation for JSON isn't a method available via the `JSON` object, e.g. `JSON.parse`, `JSON.stringify` and `JSON.validate` or something similar.

**Comment by douglascrockford** [comment]
JSON.parse does that.

**Comment by ayesham** [comment]
Sorry to comment on this closed issue. But `JSON.parse` needs to be in a try/catch to verify a valid JSON string.
