### ISSUE TITLE
cycle.js should favor less depth

### ISSUE THREAD

**Issue by svnpenn** [douglascrockford/JSON-js#96]
Thank you for this file, it is quite helpful. I have been working on my own decycle function, that produces a JSON friendly object rather than a string:

http://github.com/svnpenn/bm/blob/5970e63/libstd.js

However I noticed with cycle.js, if an object is not found, it is pushed into the output object. Subsequent copies are marked as duplicates. I feel this is not quite right. Performance wise it probably gets the best results, but I feel that the "original" sub-objects should be the ones with the least depth. As an example:

~~~
window.window
~~~

would be an "original", and:

~~~
window.window.window
~~~

would be a copy. My example is not the best but hopefully what I am asking is understood. This would take a performance hit because you couldnt build your output until the input is fully processed; alternatively you could add objects as you go, but you would need to remove them if an identical object is scanned later in the recursion with less depth.

**Comment by svnpenn** [comment]
Here is maybe a better example:

~~~js
a = {
  b: 1
};
c = {
  d: {
    e: a
  },
  e: a
};
JSON.stringify(JSON.decycle(c), 0, 2);
~~~

Result:

~~~js
"{
  "d": {
    "e": {
      "b": 1
    }
  },
  "e": {
    "$ref": "$[\"d\"][\"e\"]"
  }
}"
~~~

Desired result:

~~~
"{
  "d": {
    "e": {
      "$ref": "$[\"e\"]"
    }
  },
  "e": {
    "b": 1
  }
}"
~~~

**Comment by douglascrockford** [comment]
I don't see the value in slowing it down.

**Comment by svnpenn** [comment]
https://github.com/svnpenn/bm/issues/22
